### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q               | A
| --------------- | ---
| Bug fix?         | yes
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

🎉

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Note that the actions stuff is working correctly, on my fork, however it just won;t show on this PR until the actions config is merged to master. GitHub don't run actions when the target branch (for whatever reason).

**Comment by GrahamCampbell** [comment]
In particular, I chose actions because of the fact we can write 8.0 for the version. Travis refuse to do this... which is stupid because if we write nightly, we'd only have to update the config later, because we really did want 8.0.

**Comment by GrahamCampbell** [comment]
NB The actions run on my fork is: https://github.com/GrahamCampbell/promise/actions/runs/160365041. The coverage stuff should work on this repo. My fork just isn't enabled on scrutinizer.

**Comment by dbu** [comment]
i deleted the travis-ci hook

**Comment by GrahamCampbell** [comment]
Travis wouldn't run anyway since I deleted its config file from the repo. :)

**Comment by dbu** [comment]
i assumed it would start to error

**Comment by GrahamCampbell** [comment]
It just skips builds that have no config. It's useful when a repo has some branches only on travis and some only on actions.

**Pull request merged**
